language: java
sudo: false

install: /bin/true

jdk:
- oraclejdk8

env:
  - NEO4J_VERSION="3.3.0"

before_install:
- wget dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz
- tar -xzf neo4j-community-$NEO4J_VERSION-unix.tar.gz
- neo4j-community-$NEO4J_VERSION/bin/neo4j start
- sleep 10  # give Neo4J some time to start
- curl -v POST http://neo4j:neo4j@localhost:7474/user/neo4j/password -d"password=neo4j2"
- curl -v POST http://neo4j:neo4j2@localhost:7474/user/neo4j/password -d"password=neo4j"
- gradle wrapper
- sudo apt-get install jq
- wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

before_script:
    - wget https://services.gradle.org/distributions/gradle-2.14-bin.zip
    - unzip gradle-2.14-bin.zip
    - export GRADLE_HOME=$PWD/gradle-2.14
    - export PATH=$GRADLE_HOME/bin:$PATH

script:
- ./gradlew assemble
- ./gradlew check
- ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml